stages:
  - build
  - test
  - deploy

.before_script_test: &before_script_test
  - apt update
  - apt-get install -y --no-install-recommends rsync
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$CI_PRIVATE_KEY")
  - composer install --no-interaction --no-suggest --no-ansi --no-progress --no-dev

build:composer_install:
  stage: build
  image: mattiabasone/php:7.3-cli
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - vendor/
  script:
    - composer install --no-interaction --no-suggest --no-ansi --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 7 days

test:php73:
  stage: test
  image: mattiabasone/php:7.3-cli
  services:
    - name: mariadb:10.2.19
      alias: db
  variables:
    MYSQL_DATABASE: "app"
    MYSQL_ROOT_PASSWORD: "root"
  before_script:
    - cp .env.ci_testing .env
    - php artisan migrate
  script:
    - vendor/bin/phpunit --configuration phpunit-ci.xml

#test:php74:
#  stage: test
#  image: mattiabasone/php:7.4-rc-cli
#  allow_failure: true
#  services:
#    - name: mysql:5.7
#      alias: db
#  variables:
#    MYSQL_DATABASE: "app"
#    MYSQL_ROOT_PASSWORD: "root"
#  before_script:
#    - cp .env.ci_testing .env
#    - php artisan migrate
#  script:
#    - vendor/bin/phpunit --configuration phpunit-ci.xml

deploy:staging:
  stage: deploy
  image: mattiabasone/php:7.3-cli
  environment:
    name: staging
    url: https://staging.minepic.org
  before_script:
    - *before_script_test
  script:
    - rsync -rav -e "ssh -p$SERVER_PORT" --exclude-from=$BASE_EXCLUDE --delete $CI_PROJECT_DIR/ $SERVER_USER@$SERVER_ADDRESS:$SERVER_APP_PATH_STAG
    - ssh -p $SERVER_PORT $SERVER_USER@$SERVER_ADDRESS "sudo chmod -R 770 $SERVER_APP_PATH_STAG"
    - ssh -p $SERVER_PORT $SERVER_USER@$SERVER_ADDRESS "docker exec -t staging.minepic.org-backend php /var/www/app/artisan migrate --force"
  only:
    - staging

deploy:production:
  stage: deploy
  image: mattiabasone/php:7.3-cli
  environment:
    name: production
    url: https://minepic.org
  before_script:
    - *before_script_test
  script:
    - rsync -rav -e "ssh -p$SERVER_PORT" --exclude-from=$BASE_EXCLUDE --delete $CI_PROJECT_DIR/ $SERVER_USER@$SERVER_ADDRESS:$SERVER_APP_PATH_PROD
    - ssh -p $SERVER_PORT $SERVER_USER@$SERVER_ADDRESS "sudo chmod -R 770 $SERVER_APP_PATH_PROD"
    - ssh -p $SERVER_PORT $SERVER_USER@$SERVER_ADDRESS "docker exec -t minepic.org-backend php /var/www/app/artisan migrate --force"
  only:
    - master