stages:
  - build
  - test
  - deploy

composer_install:
  stage: build
  image: mattiabasone/php:7.3-cli
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - vendor/
  script:
    - composer install --no-interaction --no-suggest --no-ansi --no-progress
  artifacts:
    paths:
      - vendor/
    expire_in: 7 days

unit_test:php73:
  stage: test
  image: mattiabasone/php:7.3-cli
  services:
    - mysql:5.7
  variables:
    MYSQL_DATABASE: "app"
    MYSQL_ROOT_PASSWORD: "root"
  before_script:
    - cp .env.ci_testing .env
    - php artisan migrate
  script:
    - vendor/bin/phpunit --configuration phpunit-ci.xml

unit_test:php74:
  stage: test
  image: mattiabasone/php:7.4-rc-cli
  allow_failure: true
  services:
    - mysql:5.7
  variables:
    MYSQL_DATABASE: "app"
    MYSQL_ROOT_PASSWORD: "root"
  before_script:
    - cp .env.ci_testing .env
    - php artisan migrate
  script:
    - vendor/bin/phpunit --configuration phpunit-ci.xml

deploy_production:
  stage: deploy
  image: mattiabasone/php:7.3-cli
  environment:
    name: production
    url: https://minepic.org
  before_script:
    - apt update
    - apt-get install -y --no-install-recommends rsync
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$CI_PRIVATE_KEY")
  script:
    - rsync -rav -e "ssh -p$SERVER_PORT" --exclude-from=$BASE_EXCLUDE --delete $CI_PROJECT_DIR/ $SERVER_USER@$SERVER_ADDRESS:$SERVER_APP_PATH
  only:
    - master